VSystem/urls.py
from django.contrib import admin
from django.urls import path
from mainApp.views import inicio
from persona.views import get_estudiantes, registrar_persona
from curso.views import getCursos, inscribir_curso
from relacion.views import getRelacion, relacionar_curso_est
from matricula.views import getMatricula, registrar_matricula


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('lista-estudiantes/', get_estudiantes, name='lista-estudiantes'),
    path('cursos/', getCursos, name='get_cursos'),
    path('lista-cursos/', getCursos, name='lista-cursos'),
    path('registrarPersona/', registrar_persona),
    path('inscribirCurso/', inscribir_curso, name='inscribirCurso'),
    path('relacionar_curso_est/', relacionar_curso_est, name='relacionar_curso_est'),
    path('lista-relacion/', getRelacion, name='lista-relacion'),
    path('lista-matricula/', getMatricula, name='lista-matricula'),
    path('registrar_matricula/', registrar_matricula, name='registrar_matricula'),
]

matricula/models.py
from django.db import models
from relacion.models import Relacion

class Matricula(models.Model):
    
    ESTADO_CHOICES = [
        ('Activo', 'Activo'),
        ('Suspendido', 'Suspendido'),
        ('Finalizado', 'Finalizado'),
    ]
    
    relacion = models.ForeignKey(Relacion, on_delete=models.SET_NULL, null=True)
    fechaInicio = models.DateField()
    estado = models.CharField(max_length=150, choices=ESTADO_CHOICES, default='Activo')
    costo = models.DecimalField(max_digits=8, decimal_places=1)
    
    def __str__(self):
        if self.relacion is not None:
            return f'Matrícula de {self.relacion.estudiante.nombre} en {self.relacion.curso.nombre} - Estado: {self.estado} - Costo: {self.costo}'
        return "Matrícula sin relación"
   
    class Meta:
        db_table = 'Matriculas' 




    

matricula/forms.py
from django import forms
from .models import Matricula

class MatriculaForm(forms.ModelForm):
    ESTADO_CHOICES = [
        ('Activo', 'Activo'),
        ('Suspendido', 'Suspendido'),
        ('Finalizado', 'Finalizado'),
    ]

    estado = forms.ChoiceField(choices=ESTADO_CHOICES)

    class Meta:
        model = Matricula
        fields = ['estado', 'fechaInicio', 'costo', 'relacion']  

matricula/views.py
from django.shortcuts import render, redirect
from relacion.models import Relacion 
from .models import Matricula
from .forms import MatriculaForm

def getMatricula(request):
    matriculas = Matricula.objects.all()
    relaciones = Relacion.objects.all()
    return render(request, 'matriculas.html', {
        'title': 'Lista de Matrículas',
        'matriculas': matriculas,
        'relaciones': relaciones
    })
    
def matricula(request):
    data = {
        'form' : MatriculaForm()
    }
    return render(request, 'matriculas.html', data)
    
def registrar_matricula(request):
    if request.method == 'POST':
        relacion_id = request.POST.get('htrelacion')
        fechaInicio = request.POST.get('htfechaInicio')
        estado = request.POST.get('htestado')
        costo = request.POST.get('htcosto')
        
        matricula = Matricula(
            relacion_id=relacion_id,
            fechaInicio=fechaInicio,
            estado=estado,
            costo=costo,
        )
        
        matricula.save()
        return redirect('lista-matricula')


    

matricula/templates/matriculas.html
{% extends "index.html" %}
{% block content %}
<h1 style="text-align: center;">{{ title }}</h1>

<div style="text-align: right; margin-bottom: 10px;">
    <button id="showFormButton" class="btn btn-primary">Agregar nueva Matricula</button>
</div>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Estudiante</th>
            <th scope="col">Curso</th>
            <th scope="col">Fecha de inicio</th>
            <th scope="col">Estado</th>
            <th scope="col">Costo</th>
        </tr>
    </thead>
    <tbody>
        {% for matricula in matriculas %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ matricula.relacion.estudiante.nombre }} {{ matricula.relacion.estudiante.apellido }}</td>
                <td>{{ matricula.relacion.curso.nombre }}</td>
                <td>{{ matricula.fechaInicio }}</td>
                <td>
                    <span class="
                        {% if matricula.estado == 'Activo' %} estado-activo 
                        {% elif matricula.estado == 'Suspendido' %} estado-suspendido 
                        {% elif matricula.estado == 'Finalizado' %} estado-finalizado 
                        {% endif %}
                    ">
                        {{ matricula.estado }}
                    </span>
                </td>
                <td>{{ matricula.costo }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <div class="backdrop"  id="backdrop"></div>

    <section class="form-register" id="registrationForm" style="display: none;">
        <h2>Inscribir Estudiante a Curso</h2>
        <form action="{% url 'registrar_matricula' %}" method="POST">{% csrf_token %}

            <label for="id_relacion">Estudiante y Curso</label>
            <select class="controls" name="htrelacion" required>
                <option value="">Seleccione un Estudiante y Curso</option>
                {% for relacion in relaciones %}
                <option value="{{ relacion.id }}">
                    {{ relacion.estudiante.nombre }} {{ relacion.estudiante.apellido }} - {{ relacion.curso.nombre }}
                </option>
                {% endfor %}
            </select>
    
            <label for="id_fechaInicio">Fecha de Inicio</label>
            <input class="controls" type="date" name="htfechaInicio" required>
    
            <label for="id_estado">Estado</label>
            <select class="controls" name="htestado" required>
                <option value="Activo">Activo</option>
                <option value="Suspendido">Suspendido</option>
                <option value="Finalizado">Finalizado</option>
            </select>
    
            <label for="id_costo">Costo</label>
            <input class="controls" type="number" step="0.01" name="htcosto" placeholder="Costo" required>
    
            <input class="botons" type="submit" value="Guardar" />
            <button type="button" class="btn btn-primary" id="hideFormButton">Cancelar</button>
        </form>
    </section>

    <script>
        document.getElementById('showFormButton').onclick = function() {
          var form = document.getElementById('registrationForm');
          var backdrop = document.getElementById('backdrop');
          form.style.display = 'block'; 
          backdrop.style.display = 'block'; 
        };
      
        document.getElementById('hideFormButton').onclick = function() {
          var form = document.getElementById('registrationForm');
          var backdrop = document.getElementById('backdrop');
          form.style.display = 'none'; 
          backdrop.style.display = 'none'; 
        };
      </script>

{% endblock %}