VSystem/urls.py
from django.contrib import admin
from django.urls import path
from mainApp.views import inicio
from persona.views import get_estudiantes, registrar_persona
from curso.views import getCursos, inscribir_curso
from relacion.views import getRelacion, relacionar_curso_est
from matricula.views import getMatricula, registrar_matricula


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('lista-estudiantes/', get_estudiantes, name='lista-estudiantes'),
    path('cursos/', getCursos, name='get_cursos'),
    path('lista-cursos/', getCursos, name='lista-cursos'),
    path('registrarPersona/', registrar_persona),
    path('inscribirCurso/', inscribir_curso, name='inscribirCurso'),
    path('relacionar_curso_est/', relacionar_curso_est, name='relacionar_curso_est'),
    path('lista-relacion/', getRelacion, name='lista-relacion'),
    path('lista-matricula/', getMatricula, name='lista-matricula'),
    path('registrar_matricula/', registrar_matricula, name='registrar_matricula'),
]

curso/models.py
from django.db import models
from persona.models import Persona
from django.core.exceptions import ValidationError

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    capacidadMaxima = models.IntegerField(default=30)
    profesor = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True, blank=True)

    
    def clean(self):
        # Validación de capacidad máxima
        if self.capacidadMaxima <= 0:
            raise ValidationError('La capacidad máxima debe ser mayor que cero.')
        
        # Validación de rol de profesor
        if self.profesor.rol != 'Docente':
            raise ValidationError('El rol del profesor debe ser "Docente".')
    
    def __str__(self):
        if self.profesor:
           return f'{self.nombre} - {self.profesor.nombre}'
        else:
            return f'{self.nombre} - Sin Profesor Asignado'
        

    
    class Meta:
        db_table = 'curso'

curso/forms.py
from django import forms
from .models import Curso

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['nombre', 'capacidadMaxima', 'profesor']

    def clean_profesor(self):
        profesor = self.cleaned_data.get('profesor')

        # Verificar si se ha asignado un profesor antes de acceder al rol
        if profesor is not None:
            if profesor.rol == 'Estudiante':  # Verifica si el rol es 'Estudiante'
                raise forms.ValidationError('No puedes asignar a un estudiante como profesor.')
        
        # Si profesor es None, devolver None o el valor actual sin validar
        return profesor

curso/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse

from persona.models import Persona
from .models import Curso
from .forms import CursoForm

def getCursos(request):
    cursos = Curso.objects.all()
    profesores = Persona.objects.filter(rol='Docente')
    return render(request, 'cursos.html', {
        'title': 'Listado de Cursos',
        'cursos': cursos,
        'profesores': profesores  
    })
    
def curso(request):
    data = {
        'form': CursoForm()
    }
    return render(request, 'cursos.html', data)

def registrar_curso(request):
    nombre = request.POST.get()
    
def inscribir_curso(request):
    if request.method == 'POST':
        nombre = request.POST.get('txtnombre')
        capacidad_maxima = request.POST.get('txtcapacidadmaxima')
        profesor_id = request.POST.get('profesor')

        curso = Curso(nombre=nombre, capacidadMaxima=capacidad_maxima, profesor_id=profesor_id)
        curso.save()
        return redirect('get_cursos')
    
    profesores = Persona.objects.filter(rol='Docente')
    
    return render(request, 'cursos.html', {'profesores': profesores})
    
    

curso/templates/cursos.html
{% extends "index.html" %}
{% block content %}
{% load static %}
<h1 style="text-align: center;">{{ title }}</h1>

<div style="text-align: right; margin-bottom: 10px;">
<button id="showFormButton" class="btn btn-primary">Inscribir Curso</button>
</div>

<table class="table table-dark table-striped">
   <thead>
     <tr>
       <th scope="col">#</th>
       <th scope="col">Nombre</th>
       <th scope="col">Capacidad Maxima</th>
       <th scope="col">Profesor</th>
     </tr>
   </thead>
   <tbody>
     {% for curso in cursos %}
     <tr>
       <th scope="row">{{ forloop.counter }}</th>
       <td>{{ curso.nombre }}</td>
       <td>{{ curso.capacidadMaxima }}</td>
       <td>{{ curso.profesor.nombre }}</td>
     </tr>
     {% endfor %}
   </tbody>
</table>


<div class="backdrop"  id="backdrop"></div>

<!-- Formulario -->
<section class="form-register" id="registrationForm" style="display: none;">
  <h2>Inscribir Curso</h2> 
  <form action="{% url 'inscribirCurso' %}" method="POST">{% csrf_token %}
      <label for="id_nombre">Nombre del Curso</label>
      <input class="controls" type="text" name="txtnombre" placeholder="Nombre" required>

      <label for="id_capacidadMaxima">Capacidad Máxima</label>
      <input class="controls" type="number" name="txtcapacidadmaxima" placeholder="Capacidad Máxima" required>

      <label for="id_profesor">Profesor</label>
      <select class="controls" name="profesor">
        <option value="">Seleccione un Profesor</option>
        {% for profesor in profesores %}
        <option value="{{ profesor.id }}">{{ profesor.nombre }}</option>
        {% endfor %}
      </select>
      <input class="botons" type="submit" value="Guardar" />
      <button type="button" class="btn btn-primary" id="hideFormButton">Cancelar</button>
  </form>
</section>

<script>
  document.getElementById('showFormButton').onclick = function() {
    var form = document.getElementById('registrationForm');
    var backdrop = document.getElementById('backdrop');
    form.style.display = 'block'; 
    backdrop.style.display = 'block'; 
  };

  document.getElementById('hideFormButton').onclick = function() {
    var form = document.getElementById('registrationForm');
    var backdrop = document.getElementById('backdrop');
    form.style.display = 'none'; 
    backdrop.style.display = 'none'; 
  };
</script>
{% endblock %}