VSystem/urls.py
from django.contrib import admin
from django.urls import path
from mainApp.views import inicio
from persona.views import get_estudiantes, registrar_persona
from curso.views import getCursos, inscribir_curso
from relacion.views import getRelacion, relacionar_curso_est
from matricula.views import getMatricula, registrar_matricula


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('lista-estudiantes/', get_estudiantes, name='lista-estudiantes'),
    path('cursos/', getCursos, name='get_cursos'),
    path('lista-cursos/', getCursos, name='lista-cursos'),
    path('registrarPersona/', registrar_persona),
    path('inscribirCurso/', inscribir_curso, name='inscribirCurso'),
    path('relacionar_curso_est/', relacionar_curso_est, name='relacionar_curso_est'),
    path('lista-relacion/', getRelacion, name='lista-relacion'),
    path('lista-matricula/', getMatricula, name='lista-matricula'),
    path('registrar_matricula/', registrar_matricula, name='registrar_matricula'),
]

persona/models.py
from django.db import models

class Persona(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    dni = models.CharField(max_length=10)
    telefono = models.CharField(max_length=10)
    correo = models.EmailField()
    fecha_nacimiento = models.DateField()
    rol = models.CharField(max_length=20)
    create_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.nombre} {self.apellido} - {self.dni} - {self.rol}'

    class Meta:
        db_table = 'Persona'

persona/forms.py
from django import forms
from .models import Persona

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = '__all__'

persona/views.py
from urllib import request
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from .models import Persona
from .forms import PersonaForm

def persona(request):
    data = {
        'form': PersonaForm()
    }
    return render(request, 'lista-estudiantes.html', data)

def get_estudiantes(request):
    
    estudiantes = Persona.objects.filter(rol='Estudiante') 
    
    return render(request, 'lista-estudiantes.html',{
        'title': 'Lista de estudiantes ',
        'estudiantes': estudiantes
    })

def lista_personas(request):
    personas = Persona.objects.prefetch_related('cursos').filter(rol='estudiante')
    return render(request, 'persona/lista-estudiantes.html', {'personas': personas})

def registrar_persona(request):
        nombre = request.POST.get('txtnombre')
        apellido = request.POST.get('txtapellido') 
        dni = request.POST.get('numdni')  
        telefono = request.POST.get('numtelefono')
        correo = request.POST.get('correo')  
        fecha_nacimiento = request.POST.get('fecha_nacimiento')
        rol = 'Estudiante'
        
        peronas = Persona.objects.create(
            nombre = nombre,
            apellido = apellido,
            dni = dni,
            telefono = telefono,
            correo = correo,
            fecha_nacimiento = fecha_nacimiento,
            rol = rol
        )
        
        return redirect('lista-estudiantes')

persona/templates/lista-estudiantes.html
{% extends "index.html" %}
{% block content %}
<h1 style="text-align: center;">{{ title }}</h1>

<div style="text-align: right; margin-bottom: 10px;">
<button id="showFormButton" class="btn btn-primary">Inscribir Persona</button>
</div>

<table class="table table-dark table-striped">
   <thead>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap" rel="stylesheet">
     <tr>
       <th scope="col">#</th>
       <th scope="col">Nombre</th>
       <th scope="col">Apellido</th>
       <th scope="col">Documento</th>
       <th scope="col">Rol </th>
     </tr>
   </thead>
   <tbody>
     {% for estudiante in estudiantes %}
     <tr>
       <th scope="row">{{ forloop.counter }}</th>
       <td>{{ estudiante.nombre }}</td>
       <td>{{ estudiante.apellido }}</td>
       <td>{{ estudiante.dni }}</td>
       <td>{{ estudiante.rol }}</td>
     </tr>
     {% empty %}
       <tr>
           <td colspan="6">No hay estudiantes registrados.</td>
       </tr>
     {% endfor %}
   </tbody>
</table>

<div class="backdrop" id="backdrop"></div>

<section class="form-register" id="registrationForm" style="display: none;">
  <h2>Inscribir Persona</h2> 
      <form action="/registrarPersona/" method="POST">{% csrf_token %}

        <label for="id_nombre">Nombre de la persona</label>
        <input class="controls" type="text" name="txtnombre" placeholder="Nombre" required>
        
        <label for="id_apellido">Apellido de la persona</label>
        <input class="controls" type="text" name="txtapellido" placeholder="Apellido" required>

        <label for="id_dni">Dni de la persona</label>
        <input class="controls" type="text" name="numdni" placeholder="Dni" required>

        <label for="id_telefono">Numero de la persona</label>
        <input class="controls" type"text" name="numtelefono" placeholder="Telefono" required>

        <label for="id_correo">Correo de la persona</label>
        <input class="controls" type"email" name="correo" placeholder="Correo Electronico" required>

        <label for="id_fecha_nacimiento">Fecha de nacimiento de la persona</label>
        <input class="controls" type="date" name="fecha_nacimiento" placeholder="Fecha Nacimiento" required>
        
        <input class="botons" type="submit" value="Guardar" />
        <button type="button" class="btn btn-primary" id="hideFormButton">Cancelar</button>
        </div>
      </form>
    </section>

    <script>
  
      document.getElementById('showFormButton').onclick = function() {
        var form = document.getElementById('registrationForm');
        var backdrop = document.getElementById('backdrop');
        form.style.display = 'block'; 
        backdrop.style.display = 'block'; // Muestra el fondo borroso
      };
    
      document.getElementById('hideFormButton').onclick = function() {
        var form = document.getElementById('registrationForm');
        var backdrop = document.getElementById('backdrop');
        form.style.display = 'none';
        backdrop.style.display = 'none'; // Oculta el fondo borroso
      };
    </script>
 

{% endblock %}