VSystem/urls.py
from django.contrib import admin
from django.urls import path
from mainApp.views import inicio
from persona.views import get_estudiantes, registrar_persona
from curso.views import getCursos, inscribir_curso
from relacion.views import getRelacion, relacionar_curso_est
from matricula.views import getMatricula, registrar_matricula


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('lista-estudiantes/', get_estudiantes, name='lista-estudiantes'),
    path('cursos/', getCursos, name='get_cursos'),
    path('lista-cursos/', getCursos, name='lista-cursos'),
    path('registrarPersona/', registrar_persona),
    path('inscribirCurso/', inscribir_curso, name='inscribirCurso'),
    path('relacionar_curso_est/', relacionar_curso_est, name='relacionar_curso_est'),
    path('lista-relacion/', getRelacion, name='lista-relacion'),
    path('lista-matricula/', getMatricula, name='lista-matricula'),
    path('registrar_matricula/', registrar_matricula, name='registrar_matricula'),
]

relacion/models.py
from django.db import models
from persona.models import Persona
from curso.models import Curso

class Relacion(models.Model):
    estudiante = models.ForeignKey(Persona, on_delete=models.SET_NULL, null=True, 
    related_name='cursos', limit_choices_to={'rol': 'Estudiante'})
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True)
    fechaInicio = models.DateField()
    fechaFinal = models.DateField()
    estado = models.CharField(max_length=100)
    notaFinal = models.DecimalField(max_digits=3, decimal_places=2)

    def __str__(self):
        return f'{self.estudiante.nombre} - {self.estudiante.apellido} - Curso: {self.curso.nombre}'
    
    class Meta:
        db_table = 'Estudiante_Cursos'

relacion/forms.py
from django import forms
from .models import Relacion, Persona, Curso

class RelacionForm(forms.ModelForm):
    class Meta:
        model = Relacion
        fields = ['estudiante', 'curso', 'fechaInicio', 'fechaFinal', 'estado', 'notaFinal']
        
    def __init__(self, *args, **kwargs):
        super(RelacionForm, self).__init__(*args, **kwargs)
        self.fields['estudiante'].queryset = Persona.objects.filter(rol='Estudiante')
        
        self.fields['curso'].queryset = Curso.objects.all()
        
        

relacion/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse


from persona.models import Persona  
from curso.models import Curso
from .models import Relacion
from .forms import RelacionForm


def getRelacion(request):
    relaciones = Relacion.objects.all()
    estudiantes = Persona.objects.filter(rol='Estudiante')
    cursos = Curso.objects.all()
    return render(request, 'relacion.html', {
        'title': 'Relación estudiantes y curso',
        'relaciones': relaciones,
        'estudiantes' : estudiantes,
        'cursos' : cursos
        
    })
    
def relacion(request):
    data = {
        'form': RelacionForm()
    }
    return render(request, 'relacion.html', data) 

def registrar_relacion(request):
    nombre = request.POST.get()


def relacionar_curso_est(request):
    if request.method == 'POST':
        estudiante_id = request.POST.get('estudiante')
        curso_id = request.POST.get('txtcurso')
        fechaInicio = request.POST.get('fechainicio')
        fechaFinal = request.POST.get('fechafinal')
        estado = request.POST.get('txtestado')
        notaFinal = request.POST.get('notafinal')

        relacion = Relacion(
            estudiante_id=estudiante_id, 
            curso_id=curso_id, 
            fechaInicio=fechaInicio, 
            fechaFinal=fechaFinal, 
            estado=estado, 
            notaFinal=notaFinal
        )
        
        relacion.save()
        return redirect('lista-relacion')

relacion/templates/relacion.html
{% extends "index.html" %}
{% block content %}
<h1 style="text-align: center;">{{ title }}</h1>

<div style="text-align: right; margin-bottom: 10px;">
    <button id="showFormButton" class="btn btn-primary">Relacionar Estudiante</button>
</div>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Estudiante</th>
            <th scope="col">Curso</th>
            <th scope="col">Fecha inicio</th>
            <th scope="col">Fecha final</th>
            <th scope="col">Estado</th>
            <th scope="col">Nota final</th>
        </tr>
    </thead>
    <tbody>
        {% for relacion in relaciones %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ relacion.estudiante.nombre }} {{ relacion.estudiante.apellidos }}</td>
            <td>{{ relacion.curso.nombre }}</td>
            <td>{{ relacion.fechaInicio }}</td>
            <td>{{ relacion.fechaFinal }}</td>
            <td>{{ relacion.estado }}</td>
            <td>{{ relacion.notaFinal }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="backdrop" id="backdrop" style="display: none;"></div> <!-- Fondo borroso -->

<section class="form-register" id="registrationForm" style="display: none;">
    <h2>Relacionar Estudiante</h2>
    <form action="{% url 'relacionar_curso_est' %}" method="POST">{% csrf_token %}
        <label for="id_estudiante">Estudiante</label>
        <select class="controls" name="estudiante">
            <option value="">Seleccione un Estudiante</option>
            {% for estudiante in estudiantes %}
            <option value="{{ estudiante.id }}">{{ estudiante.nombre }}</option>
            {% endfor %}
        </select>

        <label for="id_curso">Curso</label>
        <select class="controls" name="txtcurso" required>
            <option value="">Seleccione un Curso</option>
            {% for curso in cursos %}
            <option value="{{ curso.id }}">{{ curso.nombre }}</option>
            {% endfor %}
        </select>

        <label for="id_fechaInicio">Fecha de Inicio</label>
        <input class="controls" type="date" name="fechainicio" placeholder="Fecha de Inicio" required>

        <label for="id_fechaFinal">Fecha de Finalización</label>
        <input class="controls" type="date" name="fechafinal" placeholder="Fecha de Finalización" required>

        <label for="id_estado">Estado</label>
        <input class="controls" type="text" name="txtestado" placeholder="Estado" required>

        <label for="id_notaFinal">Nota Final</label>
        <input class="controls" type="number" name="notafinal" placeholder="Nota Final" step="0.01" required> <!-- Usa type="number" para calificaciones numéricas -->

        <input class="botons" type="submit" value="Guardar">
        <button type="button" class="btn btn-primary" id="hideFormButton">Cancelar</button>
    </form>
</section>

<script>
    document.getElementById('showFormButton').onclick = function() {
        var form = document.getElementById('registrationForm');
        var backdrop = document.getElementById('backdrop');
        form.style.display = 'block'; 
        backdrop.style.display = 'block'; 
    };

    document.getElementById('hideFormButton').onclick = function() {
        var form = document.getElementById('registrationForm');
        var backdrop = document.getElementById('backdrop');
        form.style.display = 'none'; 
        backdrop.style.display = 'none'; 
    };
</script>
{% endblock %}